### ISSUE TITLE
What can you be helped at?

### ISSUE THREAD

**Issue by piotr-yuxuan** [autotrace/autotrace#4]
Hi @lemenkov,

Thanks a lot for the hard work you're having to ressurect this useful
library. It's been dead for the last years and I see it as quite
heroic actually to fight and get this tool back! 😃 I'm not a regular
C / C++ developer but I've found myself quite in need for this library
for a specific use case (a pet project) and I'm quite stuck without
it. This project has 50 stars by the time being, I suppose it comes
from people which also needs it.

Would you mind to write some documents to help onboarding on this
project? It might be anything to describe the algorithm implemented
here, the current general architecture, the flaws it has or the bugs
it exhibits, as well as where you are willing to head to, and which
use cases you plan to support.

As a reference for people who need autotrace to get a vector
centerline trace out of a raster picture, a gratis, online, but
proprietary tool is available here:

http://online.rapidresizer.com/tracer.php

Again, thanks a lot!

**Comment by jnweiger** [comment]
I've added an osx build to the new .travis.yml file. Seems to work well!  The syntax for the setup of the different systems is somewhat ugly, as travis does not yet support a clean separation of the sections by os.

**Comment by jnweiger** [comment]
Does it get past this point when imagemagic is not installed at all? Does it help to install glib?
Maybe you can compare with the travis build log at https://api.travis-ci.org/v3/job/415125748/log.txt
It is running 10.13.3 there though...

**Comment by jnweiger** [comment]
@ThSGM can you please post your version numbers of autoconf, libtool, pkg-config, automake,  aclocal, m4

**Comment by jnweiger** [comment]
Updated the instructions at https://github.com/jnweiger/autotrace/commit/571c4f167916101d9604547d0ec8fe4de2f433b9 -- travis build is at https://travis-ci.org/jnweiger/autotrace/jobs/420841979 for this commit.

**Comment by ThSGM** [comment]
Thanks for your reply. Okay, I've tried this on two machines. Both have issues, but rather than confuse you, I'll just start with the one that seems to go furthest. In the other one, I couldn't get past the sh command, but more on that later. 

Firstly, the new brew package installs you suggested seem to do the trick. I get through all the following commands: 

```
export PATH="/usr/local/opt/gettext/bin:$PATH"
brew install gettext intltool glib libtool autoconf automake pkg-config
brew install imagemagick graphicsmagick pstoedit
autoreconf -ivf
intltoolize --force
aclocal
sh ./configure MAGICK_CFLAGS="$(pkg-config graphicsmagick --cflags)" MAGICK_LIBS="$(pkg-config graphicsmagick --libs)"
make
```
This seemed to successfully create an autotrace executable in the directory. I was not sure what to do at this stage. I tried moving the autotrace executable to /usr/local/bin/. When I run `which autotrace` it gives me

`/usr/local/bin/autotrace`

However, when I call autotrace, it calls

```
trace' does not exist
This script is just a wrapper for autotrace.
See the libtool documentation for more information.
``` 

I'm not exactly sure how to test autotrace, but I'm essentially trying to install this to run an [Inkscape extension for centerline tracing]( https://github.com/fablabnbg/inkscape-centerline-trace). After doing the above, the extension still tells me: 

`You need to install autotrace for this extension to work! (macOS: http://macappstore.org/autotrace/ , Windows: see https://sourceforge.net/projects/autotrace/, Debian/Ubuntu: apt-get install autotrace.)
`

**Comment by jnweiger** [comment]
That is actually great progress. I deleted by accident the final command from the install instrctions. Sorry for this.  After `make` you also do `make install`

Then you should have
```which autotrace
/usr/local/bin/autotrace
autotrace -v
AutoTrace version 0.40.0.
```

**Comment by jnweiger** [comment]
[testrect.pbm.zip](https://github.com/autotrace/autotrace/files/2342850/testrect.pbm.zip)

This example tries hard to get sharp corners despite the thick lines:

`autotrace -filter-iterations 0 -error-threshold 1 -centerline testrect.pbm -output-format svg`

The result should look something like this:

```
<?xml version="1.0" standalone="yes"?>
<svg width="86" height="83">
<path style="stroke:#000000; fill:none;" d="M19 43L29 43L53 43L62 43L63 48L63 63L62 69L53 69L29 69L19 69L18 63L18 48L19 43"/>
</svg>
```
